theme = "catppuccin_mocha_nb"
[editor]
auto-format = true
# completion-timeout = 100
# completion-trigger-len = 1
# completion-auto-select = true
mouse = true
word-completion = { enable = false, trigger-length = 3 }

[editor.inline-diagnostics]
# cursor-line = "disable"
# other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-ignore = true

[editor.terminal]
command = "kitty"

[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
nnbsp = "␣"
space = "·"
tab = "→"
tabpad = "·"

[editor.whitespace.render]
nbsp = "all"
newline = "all"
nnbsp = "all"
space = "none"
tab = "all"

[keys.insert]
C-s = [":w", "save_selection"]
# esc = [":run-shell-command ~/nixos/home/misc/scripts/setrimeasciimode.sh true", "normal_mode"]

[keys.normal]
C-s = [":w", "save_selection"]
# esc = [":run-shell-command ~/nixos/home/misc/scripts/setrimeasciimode.sh true"]

