# by simla33 https://github.com/InioX/matugen-themes/pull/24
# : Manager [[[

[mgr]
cwd = { fg = "#eae1de" }

# Tab
tab_active = { fg = "#47291c", bg = "#edbca9", bold = true }
tab_inactive = { fg = "#ffdbce", bg = "#2f1409" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7bcdcd", bg = "#7bcdcd" }
marker_cut = { fg = "#c5e9e9", bg = "#c5e9e9" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a9cdcd", bg = "#a9cdcd" }

# Count
count_copied = { fg = "#002020", bg = "#c5e9e9" }
count_cut = { fg = "#002020", bg = "#c5e9e9" }
count_selected = { fg = "#47291c", bg = "#a9cdcd" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#edbca9" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#47291c", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#edbca9", fg = "#47291c", bold = true }
normal_alt  = { bg = "#504440", fg = "#d5c3bd" }

# Select mode
select_main = { bg = "#dbc1b8", fg = "#3d2d26", bold = true }
select_alt  = { bg = "#504440", fg = "#d5c3bd" }

# Unset mode
unset_main = { bg = "#a9cdcd", fg = "#123636", bold = true }
unset_alt  = { bg = "#504440", fg = "#d5c3bd" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#edbca9", bg = "#3d3836" }
progress_error = { fg = "#ffb4ab", bg = "#3d3836" }

# Permissions
permissions_t = { fg = "#a66954" }
permissions_w = { fg = "#518c8c" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#56bfbf" }
permissions_s = { fg = "#ff6b35" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#edbca9" }
active = { fg = "#a9cdcd", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#edbca9" }
value = { fg = "#eae1de" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#edbca9", bg = "#47291c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#edbca9" }
title = {}
hovered = { fg = "#c5e9e9", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3d3836" }
cand = { fg = "#edbca9" }
rest = { fg = "#47291c" }
desc = { fg = "#eae1de" }
separator = " ‚ñ∂ "
separator_style = { fg = "#eae1de" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#eae1de" }
run = { fg = "#eae1de" }
footer = { fg = "#3d2d26", bg = "#dbc1b8" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a9cdcd" }
title_warn = { fg = "#edbca9" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#eae1de" },
    { name = "*/", fg = "#edbca9" },
]

# : ]]]
