# by simla33 https://github.com/InioX/matugen-themes/pull/24
# : Manager [[[

[manager]
cwd = { fg = "#ffdad4" }

# Tab
tab_active = { fg = "#690100", bg = "#ffb4a8", bold = true }
tab_inactive = { fg = "#ffdad4", bg = "#410000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7198ff", bg = "#7198ff" }
marker_cut = { fg = "#d7e2ff", bg = "#d7e2ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#acc7ff", bg = "#acc7ff" }

# Count
count_copied = { fg = "#001a40", bg = "#d7e2ff" }
count_cut = { fg = "#001a40", bg = "#d7e2ff" }
count_selected = { fg = "#690100", bg = "#acc7ff" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#ffb4a8" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#690100", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb4a8", fg = "#690100", bold = true }
normal_alt  = { bg = "#603e39", fg = "#ebbbb4" }

# Select mode
select_main = { bg = "#ffb4a8", fg = "#690100", bold = true }
select_alt  = { bg = "#603e39", fg = "#ebbbb4" }

# Unset mode
unset_main = { bg = "#acc7ff", fg = "#002f67", bold = true }
unset_alt  = { bg = "#603e39", fg = "#ebbbb4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb4a8", bg = "#4c332f" }
progress_error = { fg = "#ffb4ab", bg = "#4c332f" }

# Permissions
permissions_t = { fg = "#ff300f" }
permissions_w = { fg = "#1360ff" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3e73ff" }
permissions_s = { fg = "#ff563b" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb4a8" }
active = { fg = "#acc7ff", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb4a8" }
value = { fg = "#ffdad4" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb4a8", bg = "#690100" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb4a8" }
title = {}
hovered = { fg = "#d7e2ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#4c332f" }
cand = { fg = "#ffb4a8" }
rest = { fg = "#690100" }
desc = { fg = "#ffdad4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ffdad4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffdad4" }
run = { fg = "#ffdad4" }
footer = { fg = "#690100", bg = "#ffb4a8" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#acc7ff" }
title_warn = { fg = "#ffb4a8" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#ffdad4" },
    { name = "*/", fg = "#ffb4a8" },
]

# : ]]]
